version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tambunraya-backend
    restart: unless-stopped
    network_mode: "host"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=raya
      - DB_PASSWORD=iFWs74BAXYNyJf4Y
      - DB_NAME=kepegawaian
      - KEYCLOAK_SERVER_URL=https://auth.bbpompky.id
      - KEYCLOAK_REALM=master
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=ontageniT1!
      - NODE_ENV=production
      - PORT=5001
      - FRONTEND_URL=https://tambun-raya.bbpompky.id
      - BACKEND_URL=https://api-tambun.bbpompky.id
      - DATA_PATH=/data
      - LOGS_PATH=/data/logs
      - UPLOADS_PATH=/data/uploads
    volumes:
      - ./data/backend:/data
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api-tambun.bbpompky.id/api
        - NEXT_PUBLIC_KEYCLOAK_ISSUER=https://auth.bbpompky.id/realms/master
        - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=kepegawaian
    container_name: tambunraya-frontend
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      # ⭐ Gunakan domain tunnel untuk NextAuth
      - NEXT_PUBLIC_API_URL=https://api-tambun.bbpompky.id/api
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=kepegawaian
      - NEXT_PUBLIC_KEYCLOAK_ISSUER=https://auth.bbpompky.id/realms/master
      - KEYCLOAK_ISSUER=https://auth.bbpompky.id/realms/master
      - KEYCLOAK_CLIENT_ID=kepegawaian
      - KEYCLOAK_CLIENT_SECRET=ryw0IYstLwPOMUomiZj6KLGeAfN5Dkhn
      - NEXTAUTH_URL=https://tambun-raya.bbpompky.id
      - NEXTAUTH_URL_INTERNAL=http://localhost:3002
      - NEXTAUTH_TRUST_HOST=true
      - NEXTAUTH_SECRET=dnpp//pRJuxPWuZsWUBX4YB0BAxORPt7dRR/MX91KEA=
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=ontageniT1!
      - DATA_PATH=/data
      - CACHE_PATH=/data/.next/cache
      - PUBLIC_UPLOADS_PATH=/data/public/uploads
    volumes:
      - ./data/frontend:/data
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - backend